In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [5]:
a.ndim

1

In [6]:
b.shape

(2, 3)

In [7]:
a.dtype

dtype('int32')

In [8]:
a.itemsize

4

In [9]:
b.itemsize

8

In [10]:
a.nbytes

12

In [11]:
b.nbytes

48

In [12]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [13]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [14]:
c[0, 0]

1

In [15]:
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
c[:, 0]

array([1, 8])

In [18]:
c[0, 1:6:2]

array([2, 4, 6])

In [19]:
c[0, 0] = 0
c

array([[ 0,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [20]:
c[:, 1] = 100
c

array([[  0, 100,   3,   4,   5,   6,   7],
       [  8, 100,  10,  11,  12,  13,  14]])

In [21]:
c[1, :] = 100
c

array([[  0, 100,   3,   4,   5,   6,   7],
       [100, 100, 100, 100, 100, 100, 100]])

In [22]:
c[1, :] = [8, 9, 10, 11, 12, 13, 14]
c

array([[  0, 100,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14]])

In [23]:
d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
d[1, 1, 1]

8

In [26]:
d[1, 1, 1] = 100
d

array([[[  1,   2],
        [  3,   4]],

       [[  5,   6],
        [  7, 100]]])

In [27]:
d[:, 1, :] = [[9, 9], [8, 8]]
d

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [28]:
e = np.zeros(5) 
e

array([0., 0., 0., 0., 0.])

In [29]:
f = np.zeros((5, 3)) 
f

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
g = np.zeros((2, 3, 4))
g

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [31]:
h = np.ones((2, 3, 4), dtype='int32')
h

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [32]:
i = np.full((2, 3), 99, dtype='float32')
i

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [33]:
h = np.full(a.shape, 4)
h

array([4, 4, 4])

In [34]:
j = np.random.rand(2, 3)
j

array([[0.2508791 , 0.47059927, 0.94407155],
       [0.51205665, 0.25074983, 0.16407452]])

In [35]:
k = np.random.random_sample(a.shape)
k

array([0.41620376, 0.13614865, 0.40887735])

In [36]:
l = np.random.randint(10, size=(3, 3))
l

array([[5, 1, 2],
       [9, 7, 4],
       [2, 7, 2]])

In [37]:
m = np.identity(5)
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
x = np.array([1, 2, 3])  # be careful when copying arrays
y = x
y[0] = 100

array([100,   2,   3])

In [41]:
x

array([100,   2,   3])

In [42]:
y

array([100,   2,   3])

In [43]:
z=x.copy()
z[0]=10000

In [44]:
x

array([100,   2,   3])

In [45]:
z

array([10000,     2,     3])

In [46]:
o = np.array([1,2,3,4])
o

array([1, 2, 3, 4])

In [47]:
o*2

array([2, 4, 6, 8])

In [48]:
o+2

array([3, 4, 5, 6])

In [49]:
o**2

array([ 1,  4,  9, 16])

In [50]:
np.cos(o)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [51]:
o

array([1, 2, 3, 4])

In [52]:
p = np.array([4,3,2,1])
o+p

array([5, 5, 5, 5])

In [53]:
q = np.full((2, 3), 2)
r = np.full((2, 3), 5)
q*r

array([[10, 10, 10],
       [10, 10, 10]])

In [56]:
s = np.full((3, 1), 7)
np.matmul(r, s)

array([[105],
       [105]])

In [57]:
t = np.mat("1 -1;1 1")  # create matrix
np.linalg.det(t)

2.0

In [58]:
np.linalg.matrix_rank(t)  #rank

2

In [60]:
np.linalg.inv(t)  #inverse

matrix([[ 0.5,  0.5],
        [-0.5,  0.5]])

In [61]:
t.T   #transpose

matrix([[ 1,  1],
        [-1,  1]])

In [62]:
u = np.mat("1 2 3;4 5 6")
u

matrix([[1, 2, 3],
        [4, 5, 6]])

In [63]:
np.min(u)

1

In [64]:
np.max(u)

6

In [65]:
np.max(u, axis=0)  # give the max of each column

matrix([[4, 5, 6]])

In [66]:
np.max(u, axis=1)  # give the max of each row

matrix([[3],
        [6]])

In [67]:
np.sum(u)

21

In [69]:
np.sum(u, axis=1)

matrix([[ 6],
        [15]])

In [70]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
after = before.reshape((8, 1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [72]:
after = before.reshape((2, 2, 2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [73]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 3))
np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.]])

In [77]:
ss = np.genfromtxt('data.txt', delimiter=',')
ss = ss.astype('int32')  # change data type
ss

array([[ 1, 32, 52, 53],
       [32, 51, 53, 65],
       [85, 46, 67, 11]], dtype=int32)

In [79]:
ss > 40

array([[False, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False]])

In [80]:
ss[ss > 40]

array([52, 53, 51, 53, 65, 85, 46, 67], dtype=int32)

In [83]:
np.any(ss > 40, axis=0)

array([ True,  True,  True,  True])

In [84]:
np.any(ss > 40, axis=1)

array([ True,  True,  True])

In [85]:
np.all(ss > 40, axis=0)

array([False, False,  True, False])

In [86]:
np.all(ss > 40, axis=1)

array([False, False, False])

In [87]:
(ss > 30) & (ss < 50)

array([[False,  True, False, False],
       [ True, False, False, False],
       [False,  True, False, False]])

In [90]:
~(ss > 30) & (ss < 50)  # ~ is not

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])