In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
%matplotlib inline

import joblib
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

In [2]:
X_test=pd.read_csv('../data/featured_data/X_test.csv')
y_test=pd.read_csv('../data/featured_data/y_test.csv')
X_test.shape,y_test.shape

((1409, 25), (1409, 1))

In [3]:
X_test = X_test.to_numpy()
y_test = y_test.to_numpy()
y_test = y_test.ravel()

In [4]:
def result_overview(y_test,y_pred):
    print("Confusion_Matrix:")
    print(str(confusion_matrix(y_test, y_pred)))
    print(classification_report(y_test, y_pred))
    print("Accuracy:" + str(accuracy_score(y_test, y_pred)))
    print("AUC_ROC:" + str(roc_auc_score(y_test, y_pred)))

### Test Voter

In [5]:
voter=joblib.load("../models/voter.m")
y_pred = voter.predict(X_test)
result_overview(y_test,y_pred)
# voter is better than the 3 single learners 

Confusion_Matrix:
[[824 237]
 [ 79 269]]
              precision    recall  f1-score   support

           0       0.91      0.78      0.84      1061
           1       0.53      0.77      0.63       348

    accuracy                           0.78      1409
   macro avg       0.72      0.77      0.73      1409
weighted avg       0.82      0.78      0.79      1409

Accuracy:0.7757274662881476
AUC_ROC:0.7748071652204058


### Test LR

In [6]:
lr=joblib.load("../models/lr.m")
y_pred = lr.predict(X_test)
result_overview(y_test,y_pred)

Confusion_Matrix:
[[797 264]
 [ 69 279]]
              precision    recall  f1-score   support

           0       0.92      0.75      0.83      1061
           1       0.51      0.80      0.63       348

    accuracy                           0.76      1409
   macro avg       0.72      0.78      0.73      1409
weighted avg       0.82      0.76      0.78      1409

Accuracy:0.7636621717530163
AUC_ROC:0.7764511358835191


### Test SVC

In [7]:
svc=joblib.load("../models/svc.m")
y_pred = svc.predict(X_test)
result_overview(y_test,y_pred)

Confusion_Matrix:
[[777 284]
 [ 63 285]]
              precision    recall  f1-score   support

           0       0.93      0.73      0.82      1061
           1       0.50      0.82      0.62       348

    accuracy                           0.75      1409
   macro avg       0.71      0.78      0.72      1409
weighted avg       0.82      0.75      0.77      1409

Accuracy:0.7537260468417317
AUC_ROC:0.7756467548506615


### Test XGBC

In [8]:
xgbc=joblib.load("../models/xgbc.m")
y_pred = xgbc.predict(X_test)
result_overview(y_test,y_pred)

Confusion_Matrix:
[[959 102]
 [174 174]]
              precision    recall  f1-score   support

           0       0.85      0.90      0.87      1061
           1       0.63      0.50      0.56       348

    accuracy                           0.80      1409
   macro avg       0.74      0.70      0.72      1409
weighted avg       0.79      0.80      0.80      1409

Accuracy:0.8041163946061036
AUC_ROC:0.7019321394910462
