In [1]:
from IPython.display import Latex

# Exercise 1 (Part 1): Knapsack problem

Minister Radin is about to finish his holidays and fly home. He carefully weighs his luggage and finds out that he can still take $W=7$ kg without paying over-weight fee. He decides to take advantage of it and look for some local products that he can sale at home for extra gain. He selects $n$ most interesting objects, weighs each of them, and bargains the price. He  then  takes  a  sheet  of  paper  and  calculates  the  best  combination  of  objects  to  buy  in  order  to  maximize  his  gain without paying over-weight fee of his luggage that is more expensive then eventual gain. Which objects should he buy? 


|item $i$ |    1    |    2    |    3    |    4    |    5    |    6 |
| --- | --- | --- | --- | --- | --- | --- | 
|weight $w_i$ |    2    |    1    |    1    |    3    |    2    |    1 | 
|gain $p_i$ |    8    |    5    |    5    |    6    |    3    |    2|
 
              

\underline{Solution:} Let us apply the dynamic programming (DP) approach to solve the above problem.	
  \begin{itemize}
  	\item \textbf{Stages $t$:} subsets of items $\{0, 1, 2, \dots, t\}, \forall t = \overline{1, n}$
  	\item \textbf{States $s_t$:} capacity used up to stage $t$
     \begin{itemize}
        \item State space: $s_t \in \{0,1,\dots, W\}$
       \end{itemize}
    \item \textbf{Action $x_t$:}  select or not item $t$, $x_t \in A_t(b) $
     \begin{itemize}
        \item Action space: $ A_t(s_t) = \left\{
    		\begin{array}{rl}
    		\{0, 1\}, & \text{if } b \geq w_t\\
    		\{0\}, & \text{otherwise} 	\end{array}
    		\right.
           $
    \end{itemize}
   \item   \textbf{System dynamics:} i.e. state transition
       		$$ s_t = \left\{
    		\begin{array}{rl}
    		s_{t-1} + w_t, & \text{if } x_t = 1\\
    		s_{t-1}, & \text{otherwise} 	\end{array}
    		\right.
    		$$  
  	\item \textbf{Instantaneous reward} 
        $$ g_t(s_t, x_t)  = \left\{
    		\begin{array}{rl}
    		p_t, & \text{if } x_t = 1\\
    		0, & \text{otherwise} 	\end{array}
    		\right.
    		$$ 
   \item \textbf{Value function $V_t(s_t)$:} maximal gain from items $0,1,\dots,t$ involving a capacity of $s_t$ kg 
   \item \textbf{Optimality equations:}
   $$ \left\{
    		\begin{array}{rl}
    		V_t(s_t) = \max \big\{ \underbrace{V_{t-1} (s_t)}_{x_t=0} ,   \underbrace{ V_{t-1} (s_t-w_{t}) + p_t }_{x_t=1}\big\}, & \forall t=\overline{1,n}, s_t =\overline{0, W} \\
    		V_0(s_0) = 0, & s_0 =\overline{0, W} 	\end{array}
    		\right.
    		$$ 
   
   \end{itemize}

<font color='red'>\textbf{Dynamic programming algorithm for the knapsack problem:}</font>

\textbf{Step 0.} Instanciate the problem under study:

In [18]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})

n = 6  # overall item's quantity
W = 7  # overall weight
w = [0, 2, 1, 1, 3, 2, 1]
p = [0, 8, 5, 5, 6, 3, 2]

\textbf{Step 1.}  Define matrix $V$ and initialize: $ V_0(s_0) =0, \forall s_0 =\overline{0, W}$

In [19]:
V = np.zeros(shape=(W+1, n+1))
V[:,0] = 0

In [20]:
V

array([[ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
       [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
       [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
       [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
       [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
       [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
       [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
       [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0]])

\textbf{Step 2.}  Recursively compute: 
                
%%latex
                $$ V_t(s_t) = \max \big\{ \underbrace{V_{t-1} (s_t)}_{x_t=0} ,   \underbrace{ V_{t-1} (s_t-w_{t}) + p_t }_{x_t=1}\big\}, \forall t=\overline{1,n}, s_t =\overline{0, W} $$ 
                
To \textit{record} the associated \textit{actions}, keep track of:
    		
$$ x_t(s_t) = \left\{
\begin{array}{rl}
    		1, & \text{if } V_{t-1} (s_t-w_t) + p_t > V_{t-1} (s_t)\\
    		0, & \text{otherwise} 	\end{array}
\right.
$$ 

In [21]:
keep_x = np.zeros(shape=(W+1, n+1))

for s in range(0, W+1):
    for t in range(1, n+1):
        if w[t] <= s:
            V[s, t] = max(V[s, t-1], V[s-w[t], t-1] + p[t])
        else:
            V[s, t] = V[s, t-1]

        ''' Record the associated actions '''
        if V[s-w[t], t] + p[t] > V[s, t-1]:
            keep_x[s, t] = 1

In [22]:
keep_x

array([[ 0.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0],
       [ 0.0,  1.0,  1.0,  0.0,  1.0,  0.0,  0.0],
       [ 0.0,  1.0,  1.0,  1.0,  0.0,  0.0,  0.0],
       [ 0.0,  1.0,  1.0,  1.0,  0.0,  0.0,  0.0],
       [ 0.0,  1.0,  1.0,  1.0,  0.0,  0.0,  0.0],
       [ 0.0,  1.0,  1.0,  1.0,  0.0,  0.0,  1.0],
       [ 0.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0],
       [ 0.0,  1.0,  1.0,  1.0,  1.0,  0.0,  0.0]])

In [23]:
V

array([[ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
       [ 0.0,  0.0,  5.0,  5.0,  5.0,  5.0,  5.0],
       [ 0.0,  8.0,  8.0,  10.0,  10.0,  10.0,  10.0],
       [ 0.0,  8.0,  13.0,  13.0,  13.0,  13.0,  13.0],
       [ 0.0,  8.0,  13.0,  18.0,  18.0,  18.0,  18.0],
       [ 0.0,  8.0,  13.0,  18.0,  18.0,  18.0,  20.0],
       [ 0.0,  8.0,  13.0,  18.0,  19.0,  21.0,  21.0],
       [ 0.0,  8.0,  13.0,  18.0,  24.0,  24.0,  24.0]])

\textbf{Step 4.}  Reconstruct the optimal solution:

In [24]:
x = np.zeros(n+1)
K = W 
for t in range(n, 0, -1):
    if keep_x[K,t] == 1:
        x[t] = 1
        K = K - w[t]  

\textbf{Step 5.}  The value of the optimal solution is given by $V_n(W)$:

In [25]:
print('The value of the optimal solution is: %d' % V[W,n])


The value of the optimal solution is: 24


In [26]:
print('The optimal solution is: ', x)
print('Minister Radin should buy the following items:')
for i in range(1, n+1):
    if x[i] > 0:
        print(i)

The optimal solution is:  [ 0.0  1.0  1.0  1.0  1.0  0.0  0.0]
Minister Radin should buy the following items:
1
2
3
4
