In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten,Dense

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.drop(labels=['CustomerId','Surname','RowNumber','Exited'],axis=1)
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [5]:
y = dataset['Exited']
y.head(5)

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
label1 = LabelEncoder()
X['Geography']=label1.fit_transform(X['Geography'])
X.head(10)

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0  Female   42       2       0.00              1   
1          608          2  Female   41       1   83807.86              1   
2          502          0  Female   42       8  159660.80              3   
3          699          0  Female   39       1       0.00              2   
4          850          2  Female   43       2  125510.82              1   
5          645          2    Male   44       8  113755.78              2   
6          822          0    Male   50       7       0.00              2   
7          376          1  Female   29       4  115046.74              4   
8          501          0    Male   44       4  142051.07              2   
9          684          0    Male   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [8]:
label2 = LabelEncoder()
X['Gender']=label1.fit_transform(X['Gender'])
X.head(10)

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   
5          645          2       1   44       8  113755.78              2   
6          822          0       1   50       7       0.00              2   
7          376          1       0   29       4  115046.74              4   
8          501          0       1   44       4  142051.07              2   
9          684          0       1   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [9]:
X = pd.get_dummies(X, drop_first=True, columns=['Geography'])
X.head(10)

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   
5          645       1   44       8  113755.78              2          1   
6          822       1   50       7       0.00              2          1   
7          376       0   29       4  115046.74              4          1   
8          501       1   44       4  142051.07              2          0   
9          684       1   27       2  134603.88              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1  
5               0        149756.71            0            1  
6               1         10062.80            0            0  
7               0        119346.88            1            0  
8               1         74940.50            0            0  
9               1         71725.73            0            0

In [10]:
X = pd.get_dummies(X, drop_first=True, columns=['Gender'])
X.head(10)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   
5          645   44       8  113755.78              2          1   
6          822   50       7       0.00              2          1   
7          376   29       4  115046.74              4          1   
8          501   44       4  142051.07              2          0   
9          684   27       2  134603.88              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  Gender_1  
0               1        101348.88            0            0         0  
1               1        112542.58            0            1         0  
2               0        113931.57            0            0         0  
3               0         93826.63            0            0         0  
4               1         79084.10            0            1         0  
5               0        149756.71            0            1         1  
6               1         10062.80            0            0         1  
7               0        119346.88            1            0         0  
8               1         74940.50            0            0         1  
9               1         71725.73            0            0         1

## Feature standardization

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size=0.2, random_state=0, stratify=y)

In [13]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [14]:
X_train

array([[-1.24021723,  0.77986083,  0.35390313, ..., -0.57812007,
        -0.57504086, -1.09665089],
       [ 0.75974873, -0.27382717,  0.35390313, ...,  1.72974448,
        -0.57504086,  0.91186722],
       [-1.72725557, -0.9443559 , -0.3390904 , ..., -0.57812007,
        -0.57504086, -1.09665089],
       ...,
       [-0.51484098,  0.87565065,  1.39339343, ...,  1.72974448,
        -0.57504086,  0.91186722],
       [ 0.73902369, -0.36961699, -1.03208393, ..., -0.57812007,
        -0.57504086, -1.09665089],
       [ 0.95663657, -1.32751517,  0.35390313, ..., -0.57812007,
         1.73900686,  0.91186722]])

In [15]:
X_test

array([[-1.95320227,  0.07734873,  0.29207754, ...,  1.72058015,
        -0.56888201, -1.09333878],
       [ 0.64884591, -1.42183934,  0.63549617, ...,  1.72058015,
        -0.56888201, -1.09333878],
       [ 0.13460714,  2.32613085,  0.29207754, ..., -0.58119931,
         1.75783377,  0.91462959],
       ...,
       [-1.19212889,  0.17104799,  1.32233342, ..., -0.58119931,
        -0.56888201,  0.91462959],
       [ 1.10137603,  1.48283756,  1.32233342, ..., -0.58119931,
         1.75783377, -1.09333878],
       [ 0.97795873, -0.76594456, -0.73817834, ..., -0.58119931,
         1.75783377, -1.09333878]])

## Build ANN

In [16]:
model = Sequential()
model.add(Dense(X.shape[1],activation='relu',input_dim=X.shape[1]))  
#1st hidden layer with 11 nodes & input layer with 11 nodes (11 features)
model.add(Dense(128,activation='relu'))  #one hidden layer, 128 units
model.add(Dense(1,activation='sigmoid')) #output layer, binary-classification

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [17]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [18]:
model.fit(X_train, y_train.to_numpy(), batch_size=10, epochs=10, verbose=1)

Epoch 1/10
8000/8000 [==============================] - 2s 285us/sample - loss: 0.4416 - acc: 0.8067
Epoch 2/10
8000/8000 [==============================] - 2s 195us/sample - loss: 0.3899 - acc: 0.8434
Epoch 3/10
8000/8000 [==============================] - 1s 187us/sample - loss: 0.3604 - acc: 0.8534
Epoch 4/10
8000/8000 [==============================] - 1s 187us/sample - loss: 0.3517 - acc: 0.8576
Epoch 5/10
8000/8000 [==============================] - 2s 188us/sample - loss: 0.3477 - acc: 0.8574
Epoch 6/10
8000/8000 [==============================] - 2s 188us/sample - loss: 0.3445 - acc: 0.8591
Epoch 7/10
8000/8000 [==============================] - 1s 185us/sample - loss: 0.3422 - acc: 0.8608
Epoch 8/10
8000/8000 [==============================] - 2s 191us/sample - loss: 0.3399 - acc: 0.8605
Epoch 9/10
8000/8000 [==============================] - 2s 193us/sample - loss: 0.3377 - acc: 0.8614
Epoch 10/10
8000/8000 [==============================] - 1s 186us/sample - loss: 0.3360 - a

## Evaluate

In [19]:
y_pred = model.predict_classes(X_test)

In [20]:
model.evaluate(X_test,y_test.to_numpy())  # loss: 0.2925  accuracy: 0.8490

2000/2000 [==============================] - 0s 42us/sample - loss: 0.3483 - acc: 0.8595


[0.348264829158783, 0.8595]

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [22]:
confusion_matrix(y_test, y_pred)

array([[1530,   63],
       [ 218,  189]], dtype=int64)

In [23]:
accuracy_score(y_test,y_pred)

0.8595