In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import to_categorical

In [2]:
X_test_origin=pd.read_csv('../data/featured_data/X_test.csv')
y_test_origin=pd.read_csv('../data/featured_data/y_test.csv')
X_test_origin.shape,y_test_origin.shape

((3024, 50), (3024, 1))

In [3]:
X_test = X_test_origin.to_numpy()
y_test = y_test_origin.to_numpy()
y_test = y_test.ravel()
X_test.shape,y_test.shape

((3024, 50), (3024,))

In [4]:
y_encoded = to_categorical(y_test)
y_encoded = y_encoded[:,1:]
y_encoded

array([[0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [5]:
model = keras.models.load_model("../models/NN.h5")

In [6]:
y_pred = model.predict_classes(X_test)

In [7]:
y_pred=y_pred+1

In [8]:
def result_overview(y_test,y_pred):
    print("Confusion_Matrix:")
    print(str(confusion_matrix(y_test, y_pred)))
    print(classification_report(y_test, y_pred))
    print("Accuracy:" + str(accuracy_score(y_test, y_pred)))

In [9]:
result_overview(y_test_origin,y_pred) 

Confusion_Matrix:
[[299  74   0   0   7   5  49]
 [119 259  11   0  55  14   0]
 [  0   2 296  25   3 111   0]
 [  0   0  12 428   0   7   0]
 [  5  33   6   0 363  11   0]
 [  0   2  43   9   3 354   0]
 [ 33   0   0   0   0   0 386]]
              precision    recall  f1-score   support

           1       0.66      0.69      0.67       434
           2       0.70      0.57      0.63       458
           3       0.80      0.68      0.74       437
           4       0.93      0.96      0.94       447
           5       0.84      0.87      0.86       418
           6       0.71      0.86      0.78       411
           7       0.89      0.92      0.90       419

    accuracy                           0.79      3024
   macro avg       0.79      0.79      0.79      3024
weighted avg       0.79      0.79      0.79      3024

Accuracy:0.7886904761904762
