In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import to_categorical

In [2]:
X_test_origin=pd.read_csv('../data/featured_data/X_test.csv')
y_test_origin=pd.read_csv('../data/featured_data/y_test.csv')
X_test_origin.shape,y_test_origin.shape

((3024, 50), (3024, 1))

In [3]:
X_test = X_test_origin.to_numpy()
y_test = y_test_origin.to_numpy()
y_test = y_test.ravel()
X_test.shape,y_test.shape

((3024, 50), (3024,))

In [4]:
y_encoded = to_categorical(y_test)
y_encoded = y_encoded[:,1:]
y_encoded

array([[0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [5]:
model = keras.models.load_model("../models/NN.h5")

In [6]:
y_pred = model.predict_classes(X_test)

In [10]:
y_pred=y_pred+1

In [11]:
def result_overview(y_test,y_pred):
    print("Confusion_Matrix:")
    print(str(confusion_matrix(y_test, y_pred)))
    print(classification_report(y_test, y_pred))
    print("Accuracy:" + str(accuracy_score(y_test, y_pred)))

In [12]:
result_overview(y_test_origin,y_pred) 

Confusion_Matrix:
[[295  91   3   0   7   2  36]
 [111 277  11   0  51   8   0]
 [  0   7 309  22   8  91   0]
 [  0   0   8 433   0   6   0]
 [  4  43   6   0 356   9   0]
 [  0   4  43  11   4 349   0]
 [ 41   5   0   0   0   0 373]]
              precision    recall  f1-score   support

           1       0.65      0.68      0.67       434
           2       0.65      0.60      0.63       458
           3       0.81      0.71      0.76       437
           4       0.93      0.97      0.95       447
           5       0.84      0.85      0.84       418
           6       0.75      0.85      0.80       411
           7       0.91      0.89      0.90       419

    accuracy                           0.79      3024
   macro avg       0.79      0.79      0.79      3024
weighted avg       0.79      0.79      0.79      3024

Accuracy:0.791005291005291
