In [3]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
%matplotlib inline

import joblib
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [4]:
X_test=pd.read_csv('../data/featured_data/X_test.csv')
y_test=pd.read_csv('../data/featured_data/y_test.csv')
X_test.shape,y_test.shape

((3024, 50), (3024, 1))

In [5]:
def result_overview(y_test,y_pred):
    print("Confusion_Matrix:")
    print(str(confusion_matrix(y_test, y_pred)))
    print(classification_report(y_test, y_pred))
    print("Accuracy:" + str(accuracy_score(y_test, y_pred)))

In [6]:
rf=joblib.load("../models/rf.m")
y_pred = rf.predict(X_test)
result_overview(y_test,y_pred)

/Users/FY/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/FY/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/FY/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


Confusion_Matrix:
[[312  69   0   0   7   3  43]
 [ 95 300  10   0  39  12   2]
 [  0   2 369  17   4  45   0]
 [  0   0   5 435   0   7   0]
 [  0  25   7   0 378   8   0]
 [  0   3  25   6   2 375   0]
 [ 14   1   0   0   0   0 404]]
              precision    recall  f1-score   support

           1       0.74      0.72      0.73       434
           2       0.75      0.66      0.70       458
           3       0.89      0.84      0.87       437
           4       0.95      0.97      0.96       447
           5       0.88      0.90      0.89       418
           6       0.83      0.91      0.87       411
           7       0.90      0.96      0.93       419

    accuracy                           0.85      3024
   macro avg       0.85      0.85      0.85      3024
weighted avg       0.85      0.85      0.85      3024

Accuracy:0.8508597883597884
