In [4]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
# import tensorflow as tf
# from tensorflow import keras
# from tensorflow.keras import Sequential
# from tensorflow.keras.layers import Flatten,Dense,Input,Dropout
import matplotlib.pyplot as plt
%matplotlib inline

import joblib
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

In [5]:
X_test=pd.read_csv('../data/featured_data/X_test.csv')
y_test=pd.read_csv('../data/featured_data/y_test.csv')
X_test.shape,y_test.shape

((23878, 48), (23878, 1))

In [6]:
X_test_NN = X_test.to_numpy()
y_test_NN = y_test.to_numpy()
y_test_NN = y_test_NN.ravel()

In [7]:
def result_overview(y_test,y_pred):
    print("Confusion_Matrix:")
    print(str(confusion_matrix(y_test, y_pred)))
    print(classification_report(y_test, y_pred))
    print("Accuracy:" + str(accuracy_score(y_test, y_pred)))
    print("AUC_ROC:" + str(roc_auc_score(y_test, y_pred)))

### Test NN

In [8]:
nn = keras.models.load_model("../models/NN.h5")

In [6]:
y_pred=nn.predict_classes(X_test_NN)

In [7]:
result_overview(y_test_NN,y_pred)

Confusion_Matrix:
[[14204   897]
 [ 1867  6910]]
              precision    recall  f1-score   support

           0       0.88      0.94      0.91     15101
           1       0.89      0.79      0.83      8777

    accuracy                           0.88     23878
   macro avg       0.88      0.86      0.87     23878
weighted avg       0.88      0.88      0.88     23878

Accuracy:0.8842449116341402
AUC_ROC:0.8639424547834185


### Test SVC

In [12]:
svc=joblib.load("../models/svc.m")

In [10]:
y_pred = svc.predict(X_test)

In [11]:
result_overview(y_test,y_pred)

Confusion_Matrix:
[[14093  1008]
 [ 1858  6919]]
              precision    recall  f1-score   support

           0       0.88      0.93      0.91     15101
           1       0.87      0.79      0.83      8777

    accuracy                           0.88     23878
   macro avg       0.88      0.86      0.87     23878
weighted avg       0.88      0.88      0.88     23878

Accuracy:0.8799731970851831
AUC_ROC:0.8607799051462207


### Test RF

In [14]:
rf=joblib.load("../models/rf.m")
y_pred = rf.predict(X_test)
result_overview(y_test,y_pred)

Confusion_Matrix:
[[14343   758]
 [ 1866  6911]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.92     15101
           1       0.90      0.79      0.84      8777

    accuracy                           0.89     23878
   macro avg       0.89      0.87      0.88     23878
weighted avg       0.89      0.89      0.89     23878

Accuracy:0.890108049250356
AUC_ROC:0.8686017660720651


### Test LGBC

In [15]:
lgbc=joblib.load("../models/lgbc.m")
y_pred = lgbc.predict(X_test)
result_overview(y_test,y_pred)

Confusion_Matrix:
[[13724  1377]
 [ 2006  6771]]
              precision    recall  f1-score   support

           0       0.87      0.91      0.89     15101
           1       0.83      0.77      0.80      8777

    accuracy                           0.86     23878
   macro avg       0.85      0.84      0.85     23878
weighted avg       0.86      0.86      0.86     23878

Accuracy:0.8583214674595863
AUC_ROC:0.8401310444126107


### Test Voter

In [12]:
voter=joblib.load("../models/voter.m")

In [13]:
y_pred = voter.predict(X_test)
result_overview(y_test,y_pred)

Confusion_Matrix:
[[14258   843]
 [ 1894  6883]]
              precision    recall  f1-score   support

           0       0.88      0.94      0.91     15101
           1       0.89      0.78      0.83      8777

    accuracy                           0.89     23878
   macro avg       0.89      0.86      0.87     23878
weighted avg       0.89      0.89      0.88     23878

Accuracy:0.8853756596029818
AUC_ROC:0.8641923048737414
